name: Java Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  retrofit-client-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permissions
        run: |
          chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :serverInteractor:testClasses

      - name: Run Tests
        run: ./gradlew :serverInteractor:test --tests "ru.hse.routemood.ControllerTest"